channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip<=25.1.1
  - numpy>=1.21.5,<1.25.0  
  - scipy<=1.15.3
  - matplotlib==3.7.2
  - seaborn==0.12.2
  - pandas==2.2.3
  - scikit-learn==1.7.0
  - joblib==1.3.2
  - cloudpickle==3.1.1

  - pip:
    - mlflow==2.19.0
    - dagshub==0.2.10
