name: CI Build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPOSITORY: daffablqs/workflow-ci  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Optional jika tetap mau update conda walau virtualenv yang dipakai
      - name: Update conda (optional)
        run: |
          conda update -n base -c defaults conda -y || echo "Conda not installed or update skipped"

      - name: Setup Python Environment and Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install mlflow docker dagshub joblib matplotlib seaborn pandas scikit-learn

      - name: Run MLflow Project with modelling.py
        run: |
          source .venv/bin/activate
          mlflow run MLProject -e train -P script_name=modelling.py

      - name: Run MLflow Project with modelling_tuning.py
        run: |
          source .venv/bin/activate
          mlflow run MLProject -e train -P script_name=modelling_tuning.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            MLProject/model
            MLProject/estimator.html
            MLProject/metric_info.json
            MLProject/training_confusion_matrix.png

      - name: Login to DockerHub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image with MLflow
        run: |
          source .venv/bin/activate
          mlflow build-docker -p MLProject -t $DOCKER_REPOSITORY:latest

      - name: Push Docker Image
        run: |
          docker push $DOCKER_REPOSITORY:latest
