name: CI Build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPOSITORY: daffablqs/workflow-ci
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          python-version: 3.11
          use-mamba: true
          cache: true
          channels: conda-forge, defaults  

      - name: Verify Conda Environment Activation
        shell: bash -l {0}
        run: |
          conda info --envs
          echo "Active environment: $CONDA_DEFAULT_ENV"
          which python
          python --version

      - name: Install additional Python dependencies
        shell: bash -l {0}
        run: |
          pip install --upgrade dagshub mlflow==2.19.0

      - name: Debug Conda Installed Packages
        shell: bash -l {0}
        run: conda list -n mlflow-env

      - name: Install Optional Packages
        shell: bash -l {0}
        run: |
          conda install -n mlflow-env numpy matplotlib seaborn --yes

      - name: Debug Package Versions
        shell: bash -l {0}
        run: |
          python -c "import numpy; print('numpy:', numpy.__version__)"
          python -c "import matplotlib; print('matplotlib:', matplotlib.__version__)"
          python -c "import seaborn; print('seaborn:', seaborn.__version__)"
          python -c "import mlflow; print('mlflow:', mlflow.__version__)"
          python -c "import dagshub; print('dagshub:', dagshub.__version__)"

      - name: Debug MLflow CLI Options
        shell: bash -l {0}
        run: |
          mlflow --version
          mlflow experiments create --help
          mlflow experiments search --help

      - name: Initialize MLflow Experiment
        shell: bash -l {0}
        run: |
          echo "Creating or verifying MLflow experiment named 'Heart Disease Classification'..."
          mlflow experiments create --experiment-name "Heart Disease Classification" || echo "Experiment already exists"
          
          # Get the experiment ID from the experiments search with proper flags and filter string
          EXPERIMENT_ID=$(mlflow experiments search --view active_only --filter-string "name = 'Heart Disease Classification'" --output json | jq -r '.[0].experiment_id')
          
          if [ -z "$EXPERIMENT_ID" ] || [ "$EXPERIMENT_ID" == "null" ]; then
            echo "Error: Experiment ID not found, aborting workflow."
            exit 1
          fi
          
          echo "Experiment ID: $EXPERIMENT_ID"
          echo "EXPERIMENT_ID=$EXPERIMENT_ID" >> $GITHUB_ENV

      - name: Debug MLflow Runs Status
        shell: bash -l {0}
        run: |
          mlflow runs list --experiment-id $EXPERIMENT_ID

      - name: Run MLflow Project with modelling.py script
        shell: bash -l {0}
        run: mlflow run MLProject -e train -P script_name=modelling.py --experiment-id $EXPERIMENT_ID

      - name: Get latest MLflow run_id
        id: mlflow_run_id
        shell: bash -l {0}
        run: |
          RUN_ID=$(mlflow runs list --experiment-id $EXPERIMENT_ID --order-by descending --max-results 1 --output json | jq -r '.[0].run_id')
          echo "Latest MLflow run ID: $RUN_ID"
          echo "::set-output name=run_id::$RUN_ID"

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            MLProject/model
            MLProject/estimator.html
            MLProject/metric_info.json
            MLProject/training_confusion_matrix.png

      - name: Build Docker Image
        shell: bash -l {0}
        run: mlflow build-docker -p MLProject -t $DOCKER_REPOSITORY:latest

      - name: Docker Login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Tag Docker Image with Commit SHA
        run: docker tag $DOCKER_REPOSITORY:latest $DOCKER_REPOSITORY:$GITHUB_SHA

      - name: Push Docker Images
        run: |
          docker push $DOCKER_REPOSITORY:latest
          docker push $DOCKER_REPOSITORY:$GITHUB_SHA
