name: MLflow CI

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Miniconda and environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        python-version: 3.11
        use-mamba: true
        cache: true
        channels: conda-forge, defaults

    - name: Verify Conda environment
      shell: bash -l {0}
      run: |
        conda info --envs
        echo "Active environment: $CONDA_DEFAULT_ENV"
        which python
        python --version

    - name: Install additional Python dependencies if needed
      shell: bash -l {0}
      run: |
        pip install mlflow dagshub

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        mlflow run MLProject --env-manager=local

    - name: Commit and push model artifact to GitHub
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add mlruns/*
        git commit -m 'Update model artifact from MLflow tracking' || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest MLflow model artifact path
      id: get_model_path
      run: |
        MODEL_PATH=$(find mlruns -type d -path "*/artifacts/random_forest_model" | sort -r | head -n 1)
        echo "Latest model path: $MODEL_PATH"
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build Docker image from latest model artifact
      run: mlflow models build-docker -m $MODEL_PATH -n msml-model

    - name: Push Docker image to Docker Hub
      run: |
        docker tag msml-model:latest ${{ secrets.DOCKER_HUB_USERNAME }}/msml-model:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/msml-model:latest
